# Generated by Django 2.2.6 on 2022-08-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True, max_length=20, verbose_name='sid')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='姓名')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='地址')),
            ],
        ),
    ]
